version: "3.8"

services:
  postgres:
    build:
      context: .
      dockerfile: docker/Dockerfile.postgres
    environment:
      POSTGRES_DB: musifydb
      POSTGRES_USER: ${POSTGRES_USER:-default_value}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-default_value}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    build:
      context: .
      dockerfile: docker/Dockerfile.minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio_storage:/data

  minioclient:
    build:
      context: .
      dockerfile: docker/Dockerfile.minioclient
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    depends_on:
      - minio

  express:
    build:
      context: .
      dockerfile: docker/Dockerfile.express
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://${POSTGRES_USER:-default_value}:${POSTGRES_PASSWORD:-default_value}@postgres:5432/musifydb
      NGINX_URL: http://localhost
      JWT_SECRET: ${JWT_SECRET:-default_value}
      EMAIL: musifymail@gmail.com
      EMAIL_PWD: ewsi lsqe shqf smcf
      MINIO_URL: minio
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - minio

  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - express

volumes:
  postgres_data:
  minio_storage:
